version: "3.8"

services:
  db_sorrisus:
    image: mysql:8.0

    container_name: sorrisus-mysql-db

    restart: always

    environment:
      MYSQL_DATABASE: sorrisus_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
