spring.application.name=sorrisus
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

zapi.instance=3EE29348F8B77178AC6212E352C1CFB5
zapi.token=7F4FBC67343F192972D43867
zapi.client-token=F86be642571ed498ca3497f4b5d75afcbS